### ISSUE TITLE
no IFDS.cpp when building SUPA through SVF

### ISSUE THREAD

**Issue by EboYu** [SVF-tools/SUPA#10]
Hi,

I try to build SUPA by SVF (the last version), it says "Cannot find source file: WPA/IFDS.cpp". It seems that SUPA and SVF are not sychronized. SVF has deleted IFDS.cpp, but SUPA not. So which version of SVF should I use for building SUPA?

Thanks,

**Comment by yuleisui** [comment]
Just fixed, please pull.

**Comment by EboYu** [comment]
Thx.
